- README.md
Close #2 
Update with some usage information
> doc(README): add description how to use the action  (#2)

- README.md
> doc(): update version doc

- .github/workflows/test.yml
- README.md
> chore(patch): patch release v0.1.3-draft

- README.md
documentation changes for new pre release
> doc(lint): increase version in README.md and fix markdownlint issues

- .templatesyncignore
add `.templatesyncignore` file
> feat(): add .tempaltesyncignore file :rocket:

- .github/workflows/actions_template_sync.yml
- README.md
> feat(self): add self as action template :rocket:

- .github/workflows/lint.yml
- .github/workflows/stale.yml
More infos about log4shell see: https://en.wikipedia.org/wiki/Log4Shell
Prevent log4shell
> sec(log4shell): bump versions 2 prevent log4shell :lock:

- README.md
- action.yml
- src/entrypoint.sh
> feat(hostname): add hostname :rocket:

- .github/workflows/actions_template_sync.yml
- .github/workflows/test.yml
- Dockerfile
- README.md
- src/Dockerfile
- src/entrypoint.sh
Close #168 
I do not like the current solution but not sure how to solve it in a different way.
> fix(cve): fix bug related to CVE-2022-24765 :lock:

- .github/workflows/actions_template_sync.yml
- README.md
> release(v0.4.0-draft) release new version :rocket:

- src/sync_template.sh
Closes #193
PR titles need to be surrounded by quotes since they will include spaces
> fix: quote PR title

- .github/workflows/actions_template_sync.yml
- README.md
> doc(v0.4.1-draft) bug fix release :zap:

- README.md
- action.yml
- src/sync_template.sh
Close #207 
now pr labels complete optional
> fix(config): fix pr_labels -> now complete optional (#207) :rocket:

- .github/workflows/actions_template_sync.yml
- README.md
> doc(release): update docs for new release :up:

- README.md
- docs/ARCHITECTURE.md
- docs/README.md
first PR for  #226 
some small diagram
> docs(architecture): (#226)  add a diagram about the code flow :pencil:

- README.md
Close #202 
first example for ssh and public repos
> docs(): add example for github action-template-sync :pencil:

- .github/workflows/actions_template_sync.yml
- README.md
> docs(): version bump :pencil:

- .github/workflows/actions_template_sync.yml
- README.md
new release with several bug fixes
> release(v0.5.2-draft) release new version :rocket:

- .github/workflows/actions_template_sync.yml
- README.md
> doc(): update docs for release v0.5.3-draft :up:

- src/sync_template.sh
> fix(): #285 fix empty commit exit with error :bug:

- README.md
> doc :memo: add badges (#226)

- .github/workflows/test_pat.yml
- .github/workflows/test_ssh.yml
- .github/workflows/test_ssh_gitlab.yml
Close #312 
add a condition to the part where secrets are needed
> fix: :bug: run of workflows in forked repos (#312)

- README.md
Made clear that there are 2 different solutions for private repos
Signed-off-by: George <31376482+george-gca@users.noreply.github.com>
> Improved private template repository docs

- README.md
part of #226 
add some feature documentation
> doc: :memo: document the features (#226)

- .github/workflows/test.yml
- README.md
- action.yml
- src/sync_template.sh
> :sparkles: (#338) use upstream default branch instead of configured

- .markdownlintrc
- README.md
Close #320 
add a comparison with other tools
> :memo: (#320) add comparison with other tools

- README.md
just fixed a few typos and other small changes in README.md
> doc: fixed a few typos and other small changes

- .github/workflows/push_docker.yml
- .github/workflows/release.yml
- .github/workflows/release_please.yml
- .github/workflows/release_test_docker_images.yml
- README.md
- docs/DOCKER.md
- docs/README.md
> fix: :bug: (#388) issue with docker push

- README.md
Close #424 
This PR adds
- how to enable modifications of workflow files
- how to enable checkout of submodules
to docs.
> docs: enable this workflow to modify workflow files

- README.md
> docs: :memo: small docs fix - docker

- .github/workflows/test_hooks.yml
- README.md
- src/sync_common.sh
- templatesync.yml
Close #468 
possible to use github env variables
> feat(#468): :sparkles: enable usage of github env variables within hooks

- README.md
- src/sync_template.sh
Close #476 
there are edge cases for the output variables
> fix(#476): :bug: output variable edge cases

- README.md
- src/entrypoint.sh
- src/sync_template.sh
Just a small restructuring of the code
> refact: :technologist: small restructure of the code

- README.md
- src/sync_template.sh
Close #510 
- fix: :bug: issue with blank lines within `.templatesyncignore`
> fix(#510): :bug: issue with blank lines within .templatesyncignore

- README.md
- action.yml
- docker-compose.yml
- src/sync_template.sh
Close #523 
new option to be able to delete branches on pr cleanup or keep them
> feat(#523): :sparkles: delete branches on pr cleanup

- .devcontainer/docker-compose.yml
- README.md
- action.yml
- src/sync_template.sh
Part of #547 
add ability to also sync tags
> feat(#547): :sparkles: add option to include git tags

- .github/FUNDING.yml
just a small removal of some funding parameters
> docs: remove fundings

- README.md
- src/sync_template.sh
Close #592 add documentation about changing the target branch.
> docs(#592): add documentation about changing the target branch

- src/sync_template.sh
> fix(#634)：handle Windows line endings in .templatesyncignore file

- README.md
> docs(#627): add documentation about persist credentials for the checkout action
