Dockerfile, README.md, src/sync_template.sh
Close #70 
- Added optional operation which unstages files from a `.templatesyncignore` file present in the repository. I took inspiration from this [StackOverflow answer](https://stackoverflow.com/a/15399452).
- The `.templatesyncignore` follows the glob pattern as desired.
- Updated `README` to document ignoring of files.
=> Add option to ignore files

README.md, action.yml, src/sync_template.sh
Close #236
This PR enables you to change the commit message in the created pull request
=> feat: make commit msg configurable

README.md, src/sync_template.sh
Close #250 
Fix issue #250 with overwritten .templatesyncignore files from tpl repository.
=> fix(sync-template): fix issue with .templatesyncignore conflicts

.all-contributorsrc, README.md, docs/ARCHITECTURE.md, src/sync_template.sh
Close #249
Firstly search for `.templatesyncignore` and `.templateversionrc` inside .github folder. If not found, inside the root.
=> feat: config files inside .GitHub folder

src/sync_template.sh
=> fix(sync-template): typo in TEMPLATE_SYNC_IGNORE_FILE_PATH variables

src/sync_template.sh
Close #267 
I forgot to change the IF orders so that the check about .github folder comes before the "Restore Ignore File"
=> fix(sync-template): IF order

.github/workflows/test.yml, .github/workflows/test_pat.yml, Dockerfile, README.md, action.yml, src/Dockerfile, src/entrypoint.sh, src/sync_template.sh
Close #238
With this PR `gh` will be used to authenticate the repository by the used `GITHUB_TOKEN`.
This change is tested against GitHub Enterprise v3.5. It would be lovely if you could test it also against your setup on github.com.
=> feat(gh-auth): add gh auth login and credential helper

.github/workflows/actions_template_sync.yml, .github/workflows/test_ssh_gitlab.yml, README.md, action.yml, src/entrypoint.sh
Close #278 
bug fix, now other git providers (e.g. GitLab) are able to be used with e.g. ssh.
=> bug fix version bump 0.7.1-draft

README.md
you have to use the generated token with the checkout step as well otherwise the source repository isn't readable.
this isn't clear from the current documentation.
=> improve github app documentation

README.md
Close #357
This will fix a checkout issue when using a GitHub PAT.
I also renamed the PAT variable from `SOURCE_REPO_PAT` to `CUSTOM_GITHUB_PAT` in order to avoid match overlap with `SOURCE_REPO_PATH`.
=> fix: checkout action using a github pat

src/sync_template.sh
when there is an .templatesyncignore file present within source repository but not in target repo, the program stopped
Close #375 
=> fix: :bug: (#375) fix edge case with .templatesyncignore

src/sync_template.sh
Close #380
will ignore possible merge issues on pull from remote repository.
=> fix: :bug: (#380) small fix related to remote file mode changes

.github/workflows/actions_template_sync.yml, .github/workflows/release_please.yml, README.md
Close #432 
support of major/minor tags
=> feat: :construction_worker: (#432) support major/minor tags

README.md, docs/ARCHITECTURE.md, src/sync_template.sh
This adds a new hook `precommit` right before the code is committed.  This is done to avoid having to re-commit any changes in the `prepush` hook.
=> feat(#440): :sparkles:  add precommit hook

README.md, action.yml, src/sync_common.sh, src/sync_template.sh
Close #401 
- add option to force file delete
- remove `--squash` from default pull options
**Status:** needs testing
=> feat!: :sparkles: (#401) add option to force file deletion

Dockerfile, Makefile, README.md, action.yml, docker-compose.yml, src/Dockerfile, src/entrypoint.sh, src/gpg_no_tty.sh, src/sync_common.sh, src/sync_template.sh
Close #204 
add possibility to sign commits
**Status:** somehow the user is still `unverified`
=> feat: :sparkles: (#204) gpg sign

.github/workflows/actions_template_sync.yml, Dockerfile, src/Dockerfile, src/sync_template.sh
Close #461 
now pull request labels are supported when they contain a space and emoji
=> fix(#461): :bug: issue with pull request labels with emoji and space

src/sync_template.sh
fix an edge case.
Sometimes it seems `gh` cli does not return the right result
=> fix: :bug: try catch for edge cases

.github/workflows/test.yml, README.md, src/sync_template.sh
Close #472 
define output variable
=> feat(#472): :sparkles: define output

README.md, action.yml, src/sync_template.sh
Close #477 
now with brand new input parameter for the PR body
=> feat(#477): :sparkles: add input parameter for pr body

README.md, action.yml, src/sync_common.sh, src/sync_template.sh
Close #467 
now possible to use hooks within action parameters.
e.g.
```yml
- name: Test action step
uses: AndreasAugustin/actions-template-sync@v1
with:
source_repo_path: AndreasAugustin/template.git
upstream_branch: main
is_dry_run: true
is_allow_hooks: true
hooks: >
prepull:
commands:
- echo 'hi, we are within the prepull phase'
- echo 'maybe you want to do adjustments on the local code'
```
=> feat(#467): :sparkles: hooks now within action inputs

src/entrypoint.sh, src/sync_template.sh
- some more functions
- preparations for future cases and issues
=> refact: :technologist: some refactoring

.github/workflows/test_all.yml, .github/workflows/test_steps.yml, Dockerfile, README.md, action.yml, src/sync_template.sh, templatesync.yml
Close #478 
add possibility to execute single parts of the action.
=> feat(#478): :sparkles: possible to execute single steps

src/sync_template.sh
Close #529 
- fix(#529) :bug: issue when using force push pr together with pr cleanup when a merge hasn't been performed
=> fix(#529): :bug: edge case with branch cleanup and force push

Dockerfile, Makefile
mitigate issues with changed `docker-compose` command
=> chore: :technologist: update docker commands

README.md
Hello guys, im configuring this action in my project and i found this typo:
So this PR fix the typo in the README:
Best regards,
Murilo Chianfa
=> Fixing passphrase typo

README.md
Close #566 
add documentation related GHES
=> docs(#566): add docs for GHES

src/sync_template.sh
Close #573 
Correct way to handle bash arguments is using bash array.
Tested with following script
```
#!/bin/bash
set -ex
function push () {
local branch=$1
local is_force=$2
local is_with_tags=$3
args=(--set-upstream origin "${branch}")
if [ "$is_force" == true ] ; then
args+=(--force)
fi
if [ "$is_with_tags" == true ] ; then
args+=(--tags)
fi
git push "${args[@]}"
}
push "main" false false
push "main" true false
push "main" false true
push "main" true true
```
=> fix: incorrect argument passing to git push

.github/workflows/test.yml
update tests to have a real push to get notified if things like #573 are not working anymore
=> chore(#573): add tests with real push

src/entrypoint.sh
Close #591 
add missing precheck for gh cli
=> fix(#591): add missing gh cli precheck

src/sync_template.sh
Close #551 
Fix issue with force deletion of files.
Checking #401 https://github.com/AndreasAugustin/actions-template-sync/pull/435/files the issue lies in some refactorings and race conditions. With the current implementation it checked the deleted files for an interval between the same hash what does not make any sense
=> fix(#551): fix issue with file deletion
